linters:
  enable:
    - goimports
    - revive
    - govet
    - unused
    - gosimple
    - errcheck
    - ineffassign
    - staticcheck
    - goconst
    - dupl
    - exhaustive
    - gocognit
    - godot
    - godox
    - importas
    - nilerr
    - prealloc
  disable:
    - typecheck