package tkem

import (
	"bytes"
	"crypto/rand"
	"os"
	"path/filepath"
	"go/ast"
	"go/parser"
	"go/token"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/luxfi/threshold/internal/test"
	"github.com/luxfi/threshold/pkg/math/polynomial"
	"github.com/luxfi/threshold/pkg/party"
	"github.com/luxfi/threshold/pkg/protocol"
	"github.com/luxfi/threshold/protocols/frost"
	"github.com/luxfi/threshold/protocols/frost/keygen"
)

// The committee this package is specified against: 3 of 5.
//
// frostDegree is what FROST's Keygen takes — the polynomial degree, which is
// one less than the number of parties needed. Every conversion between the two
// conventions goes through FromKeygen; this constant exists so the tests state
// the operating point in the units the caller thinks in.
const (
	n            = 5
	quorum       = 3
	frostDegree  = quorum - 1
	testLabel    = "lux/kms/dek/secret-42"
	altTestLabel = "lux/kms/dek/secret-43"
)

func ids() []party.ID { return []party.ID{"a", "b", "c", "d", "e"} }

// runKeygen runs the real dealerless FROST distributed key generation across n
// simulated parties, over the network harness, with all three rounds actually
// executed. There is no dealer anywhere in this function: each party samples
// its own polynomial and the group key emerges from the sum of their public
// commitments.
func runKeygen(t *testing.T) map[party.ID]*keygen.Config {
	t.Helper()
	parties := ids()
	results, err := test.RunProtocol(t, parties, []byte("tkem-dkg-test"), func(id party.ID) protocol.StartFunc {
		return frost.Keygen(Curve(), id, parties, frostDegree)
	})
	if err != nil {
		t.Fatalf("frost keygen: %v", err)
	}
	cfgs := make(map[party.ID]*keygen.Config, n)
	for id, r := range results {
		cfg, ok := r.(*keygen.Config)
		if !ok {
			t.Fatalf("party %s produced %T, want *keygen.Config", id, r)
		}
		cfgs[id] = cfg
	}
	if len(cfgs) != n {
		t.Fatalf("keygen produced %d configs, want %d", len(cfgs), n)
	}
	return cfgs
}

// groupAndShares converts every party's key generation result into this
// package's view. Every party must agree on the public description, which is
// checked here rather than assumed.
func groupAndShares(t *testing.T, cfgs map[party.ID]*keygen.Config) (Group, map[party.ID]Share) {
	t.Helper()
	var g Group
	shares := make(map[party.ID]Share, len(cfgs))
	for _, id := range ids() {
		gi, sh, err := FromKeygen(cfgs[id])
		if err != nil {
			t.Fatalf("FromKeygen(%s): %v", id, err)
		}
		if g.PublicKey == nil {
			g = gi
		} else if !g.PublicKey.Equal(gi.PublicKey) {
			t.Fatalf("party %s disagrees about the group public key", id)
		}
		if gi.Threshold != quorum {
			t.Fatalf("party %s reports threshold %d, want %d parties", id, gi.Threshold, quorum)
		}
		shares[id] = sh
	}
	return g, shares
}

func partialsFrom(t *testing.T, shares map[party.ID]Share, subset []party.ID, ct *Ciphertext) []*Partial {
	t.Helper()
	out := make([]*Partial, 0, len(subset))
	for _, id := range subset {
		p, err := PartialDecapsulate(rand.Reader, shares[id], ct)
		if err != nil {
			t.Fatalf("partial from %s: %v", id, err)
		}
		out = append(out, p)
	}
	return out
}

// combinations returns every k-subset of the committee.
func combinations(all []party.ID, k int) [][]party.ID {
	var out [][]party.ID
	var rec func(start int, cur []party.ID)
	rec = func(start int, cur []party.ID) {
		if len(cur) == k {
			cp := make([]party.ID, k)
			copy(cp, cur)
			out = append(out, cp)
			return
		}
		for i := start; i < len(all); i++ {
			rec(i+1, append(cur, all[i]))
		}
	}
	rec(0, nil)
	return out
}

// TestClaim1_QuorumAgreement — every quorum decapsulates the key the
// encapsulator produced. This is the property that decides whether the design
// is usable: if two quorums disagreed, a secret sealed while one set of nodes
// was up could not be opened when a different set was up.
//
// Exhaustive over all C(5,3) = 10 quorums, against a key generated by the real
// dealerless DKG.
func TestClaim1_QuorumAgreement(t *testing.T) {
	g, shares := groupAndShares(t, runKeygen(t))

	ct, want, err := Encapsulate(rand.Reader, g.PublicKey, []byte(testLabel))
	if err != nil {
		t.Fatalf("encapsulate: %v", err)
	}
	if len(want) != KeyLen {
		t.Fatalf("key is %d bytes, the AES-256-GCM envelope needs %d", len(want), KeyLen)
	}

	quorums := combinations(ids(), quorum)
	if len(quorums) != 10 {
		t.Fatalf("expected 10 quorums for C(5,3), got %d", len(quorums))
	}
	for _, q := range quorums {
		got, err := Combine(g, ct, partialsFrom(t, shares, q, ct))
		if err != nil {
			t.Fatalf("quorum %v: combine: %v", q, err)
		}
		if !bytes.Equal(got, want) {
			t.Fatalf("quorum %v decapsulated a DIFFERENT key than the encapsulator produced", q)
		}
	}
	t.Logf("all %d quorums recovered the encapsulated key", len(quorums))
}

// TestClaim2_BelowThreshold — a coalition below the threshold cannot
// decapsulate. This is the whole reason to split: an attacker holding t-1 nodes
// learns nothing usable.
//
// The interesting case is not the honest one. It is the attacker who LIES about
// the threshold so that the combiner interpolates over too few points; that
// must still not produce the key.
func TestClaim2_BelowThreshold(t *testing.T) {
	g, shares := groupAndShares(t, runKeygen(t))
	ct, want, err := Encapsulate(rand.Reader, g.PublicKey, []byte(testLabel))
	if err != nil {
		t.Fatalf("encapsulate: %v", err)
	}

	subsets := combinations(ids(), quorum-1)
	for _, sub := range subsets {
		partials := partialsFrom(t, shares, sub, ct)

		if _, err := Combine(g, ct, partials); err == nil {
			t.Fatalf("subset %v of size %d decapsulated — below-threshold secrecy is broken", sub, quorum-1)
		}

		// Lie about the threshold: claim the committee only ever needed t-1.
		weakened := Group{Threshold: quorum - 1, PublicKey: g.PublicKey, VerificationShares: g.VerificationShares}
		got, err := Combine(weakened, ct, partials)
		if err != nil {
			continue // refused outright, which is also a pass
		}
		if bytes.Equal(got, want) {
			t.Fatalf("subset %v recovered the REAL key with %d shares — the threshold is a fiction", sub, quorum-1)
		}
	}
	t.Logf("all %d subsets of size %d failed to recover the key", len(subsets), quorum-1)
}

// TestClaim3_ForgedPartial is the load-bearing test, and the direct descendant
// of the defect found in the threshold-BLS aggregator: that code interpolated
// partial signatures without checking them, so a single dishonest party could
// steer the result into a well-formed but WRONG value.
//
// Here a party substitutes a partial computed under a key it made up. Combine
// must refuse and name it. This test fails if the proof check in Combine is
// removed — that is the mutation it exists to catch.
func TestClaim3_ForgedPartial(t *testing.T) {
	g, shares := groupAndShares(t, runKeygen(t))
	ct, want, err := Encapsulate(rand.Reader, g.PublicKey, []byte(testLabel))
	if err != nil {
		t.Fatalf("encapsulate: %v", err)
	}
	q := ids()[:quorum]
	partials := partialsFrom(t, shares, q, ct)

	// A rogue share: a scalar this party is not entitled to, with a
	// self-consistent proof under it. Every field is internally valid; only the
	// binding to the published verification share is wrong.
	rogue, err := randScalar(rand.Reader)
	if err != nil {
		t.Fatalf("rogue scalar: %v", err)
	}
	forged, err := PartialDecapsulate(rand.Reader, Share{ID: q[0], Secret: rogue}, ct)
	if err != nil {
		t.Fatalf("rogue partial: %v", err)
	}
	partials[0] = forged

	key, err := Combine(g, ct, partials)
	if err == nil {
		t.Fatalf("a forged partial produced a key (%x) instead of an error — "+
			"one dishonest node could make the store unreadable", key)
	}
	var bad ErrBadPartial
	if !asErrBadPartial(err, &bad) {
		t.Fatalf("expected ErrBadPartial, got %T: %v", err, err)
	}
	if bad.Culprit != q[0] {
		t.Fatalf("blamed %q, the forger was %q", bad.Culprit, q[0])
	}

	// Confirm the danger is real rather than hypothetical: interpolating the
	// forged partial WITHOUT the proof check yields a well-formed 32-byte key
	// that is not the right one. That is what the check is buying.
	unchecked := combineWithoutProofs(t, g, ct, partials)
	if bytes.Equal(unchecked, want) {
		t.Fatal("the forged partial happened to reproduce the real key — test is not exercising the hazard")
	}
	if len(unchecked) != KeyLen {
		t.Fatalf("unchecked combine produced %d bytes, expected a well-formed but wrong %d-byte key", len(unchecked), KeyLen)
	}
	t.Logf("forged partial yields a well-formed but WRONG key when unchecked (%x...); the proof caught it and named %q", unchecked[:8], bad.Culprit)
}

// combineWithoutProofs is the mutation Claim 3 defends against, written out in
// the test so the hazard is demonstrated rather than asserted. It is the same
// interpolation Combine does, minus the verification.
func combineWithoutProofs(t *testing.T, g Group, ct *Ciphertext, partials []*Partial) []byte {
	t.Helper()
	partyIDs := make([]party.ID, len(partials))
	for i, p := range partials {
		partyIDs[i] = p.ID
	}
	lambda := polynomial.Lagrange(Curve(), partyIDs)
	S := Curve().NewPoint()
	for _, p := range partials {
		S = S.Add(lambda[p.ID].Act(p.D))
	}
	key, err := deriveKey(ct.R, S, ct.Label)
	if err != nil {
		t.Fatalf("unchecked derive: %v", err)
	}
	return key
}

// TestClaim4_SecretIsNeverAssembled is the claim the whole exercise exists for.
//
// It cannot prove a hardness assumption, and does not pretend to. What it does
// prove is that the private key is absent from everything the protocol ever
// produces: it computes x out of band, from all five shares at once — something
// no participant can do — and then checks that its encoding appears in no
// ciphertext, no partial, no derived key, and in no party's own state.
//
// A regression that reintroduced assembly, for instance a helper that
// interpolated shares to a scalar and used it directly, would put x's bytes
// into one of those places and fail here.
func TestClaim4_SecretIsNeverAssembled(t *testing.T) {
	cfgs := runKeygen(t)
	g, shares := groupAndShares(t, cfgs)

	// Out-of-band reconstruction, available only to the test because it holds
	// every share simultaneously. This is precisely the capability no machine
	// in the deployment has.
	x := Curve().NewScalar()
	lambda := polynomial.Lagrange(Curve(), ids())
	for _, id := range ids() {
		x = x.Add(cloneScalar(lambda[id]).Mul(shares[id].Secret))
	}
	if !x.ActOnBase().Equal(g.PublicKey) {
		t.Fatal("out-of-band reconstruction did not reproduce the public key; the test's own premise is broken")
	}
	xBytes, err := x.MarshalBinary()
	if err != nil {
		t.Fatalf("marshal x: %v", err)
	}

	// Everything the protocol produces, in one place.
	ct, key, err := Encapsulate(rand.Reader, g.PublicKey, []byte(testLabel))
	if err != nil {
		t.Fatalf("encapsulate: %v", err)
	}
	partials := partialsFrom(t, shares, ids()[:quorum], ct)

	artifacts := map[string][]byte{
		"ciphertext.R":    enc(ct.R),
		"ciphertext.RBar": enc(ct.RBar),
		"ciphertext.E":    mustMarshal(t, ct.E),
		"ciphertext.F":    mustMarshal(t, ct.F),
		"encapsulated":    key,
		"group.PublicKey": enc(g.PublicKey),
	}
	for _, p := range partials {
		artifacts["partial."+string(p.ID)+".D"] = enc(p.D)
		artifacts["partial."+string(p.ID)+".E"] = mustMarshal(t, p.E)
		artifacts["partial."+string(p.ID)+".F"] = mustMarshal(t, p.F)
	}
	for id, sh := range shares {
		artifacts["share."+string(id)] = mustMarshal(t, sh.Secret)
		artifacts["verification."+string(id)] = enc(g.VerificationShares[id])
	}
	combined, err := Combine(g, ct, partials)
	if err != nil {
		t.Fatalf("combine: %v", err)
	}
	artifacts["combined"] = combined

	for name, blob := range artifacts {
		if bytes.Contains(blob, xBytes) {
			t.Fatalf("%s contains the private key — it was assembled somewhere it must not be", name)
		}
	}

	// And no party's share IS the key, which is the degenerate way to hold it.
	for id, sh := range shares {
		if sh.Secret.Equal(x) {
			t.Fatalf("party %s holds the private key outright", id)
		}
	}
	t.Logf("checked %d protocol artifacts across a real %d-of-%d run; the private key appears in none", len(artifacts), quorum, n)
}

// TestClaim4_NoReconstructionInSource is the structural half of Claim 4. The
// runtime test can only observe values that exist; this one refuses the code
// shapes that would create them, by reading the package's syntax tree rather
// than its text — prose about reconstruction is fine, code that does it is not.
//
// Two invariants, both mechanical:
//
//   - No exported function returns a curve.Scalar. The private key is a scalar,
//     so a package that never hands one out cannot hand out the private key.
//   - No exported function accepts more than one Share. Assembling the key needs
//     several shares at once; an API that only ever sees one cannot do it.
func TestClaim4_NoReconstructionInSource(t *testing.T) {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate package source")
	}
	dir := filepath.Dir(thisFile)
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read package dir: %v", err)
	}

	forbidden := map[string]bool{"reconstruct": true, "Reconstruct": true, "recoverSecret": true, "masterSecret": true, "assembleKey": true}
	fset := token.NewFileSet()
	var checked, exported int
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0) // 0 = drop comments
		if err != nil {
			t.Fatalf("parse %s: %v", name, err)
		}
		checked++

		ast.Inspect(f, func(node ast.Node) bool {
			if id, ok := node.(*ast.Ident); ok && forbidden[id.Name] {
				t.Fatalf("%s declares or calls %q — the package must never assemble the private key", name, id.Name)
			}
			fn, ok := node.(*ast.FuncDecl)
			if !ok || !fn.Name.IsExported() {
				return true
			}
			exported++
			if fn.Type.Results != nil {
				for _, res := range fn.Type.Results.List {
					if typeString(res.Type) == "curve.Scalar" {
						t.Fatalf("%s: exported %s returns a curve.Scalar — that is the shape of the private key",
							name, fn.Name.Name)
					}
				}
			}
			for _, param := range fn.Type.Params.List {
				if ts := typeString(param.Type); ts == "[]Share" || strings.HasSuffix(ts, "]Share") {
					t.Fatalf("%s: exported %s takes several Shares at once — that is the shape of reconstruction",
						name, fn.Name.Name)
				}
			}
			return true
		})
	}
	if checked == 0 || exported == 0 {
		t.Fatalf("structural check examined %d files and %d exported functions", checked, exported)
	}
	t.Logf("structural check passed over %d source files, %d exported functions: none returns a scalar, none takes a share set", checked, exported)
}

// typeString renders an AST type expression compactly enough to compare.
func typeString(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.SelectorExpr:
		return typeString(v.X) + "." + v.Sel.Name
	case *ast.StarExpr:
		return "*" + typeString(v.X)
	case *ast.ArrayType:
		return "[]" + typeString(v.Elt)
	case *ast.MapType:
		return "map[" + typeString(v.Key) + "]" + typeString(v.Value)
	default:
		return ""
	}
}

// TestRefreshPreservesGroupPublicKey is the invariant that everything sealed
// depends on. Refresh rerandomises every share while leaving the group key
// alone; if it did not, every ciphertext ever written would become unopenable,
// which is the worst outcome available here.
//
// The strong half of the test is the second one: a ciphertext sealed BEFORE the
// refresh is opened by shares that only exist AFTER it.
func TestRefreshPreservesGroupPublicKey(t *testing.T) {
	before := runKeygen(t)
	gBefore, sharesBefore := groupAndShares(t, before)

	// Snapshot the share BYTES. FROST's refresh accumulates into the scalar the
	// config already holds, so config.PrivateShare is mutated in place and a
	// pointer captured now would show the post-refresh value. Comparing bytes
	// taken before the run is the only way to see whether anything moved.
	beforeBytes := make(map[party.ID][]byte, n)
	for _, id := range ids() {
		beforeBytes[id] = mustMarshal(t, sharesBefore[id].Secret)
	}
	pubBefore := clonePoint(gBefore.PublicKey)

	// Seal something under the pre-refresh key.
	ct, want, err := Encapsulate(rand.Reader, gBefore.PublicKey, []byte(testLabel))
	if err != nil {
		t.Fatalf("encapsulate: %v", err)
	}

	parties := ids()
	results, err := test.RunProtocol(t, parties, []byte("tkem-refresh-test"), func(id party.ID) protocol.StartFunc {
		return frost.Refresh(before[id], parties)
	})
	if err != nil {
		t.Fatalf("frost refresh: %v", err)
	}
	after := make(map[party.ID]*keygen.Config, n)
	for id, r := range results {
		cfg, ok := r.(*keygen.Config)
		if !ok {
			t.Fatalf("party %s produced %T after refresh", id, r)
		}
		after[id] = cfg
	}
	gAfter, sharesAfter := groupAndShares(t, after)

	if !pubBefore.Equal(gAfter.PublicKey) {
		t.Fatal("refresh CHANGED the group public key — every sealed secret is now unopenable")
	}

	// The shares must actually have moved, or "refresh" refreshed nothing and
	// a stolen share is still valid.
	var moved int
	for _, id := range ids() {
		if !bytes.Equal(beforeBytes[id], mustMarshal(t, sharesAfter[id].Secret)) {
			moved++
		}
	}
	if moved != n {
		t.Fatalf("only %d of %d shares changed — refresh is not rerandomising", moved, n)
	}

	// The load-bearing half: post-refresh shares open a pre-refresh ciphertext.
	for _, q := range combinations(ids(), quorum) {
		got, err := Combine(gAfter, ct, partialsFrom(t, sharesAfter, q, ct))
		if err != nil {
			t.Fatalf("post-refresh quorum %v: %v", q, err)
		}
		if !bytes.Equal(got, want) {
			t.Fatalf("post-refresh quorum %v recovered a different key — refresh broke the seal", q)
		}
	}

	// And a share from the OLD epoch must no longer work alongside new ones —
	// that is what makes refresh worth doing. The old share is rebuilt from the
	// bytes snapshotted above, since the refresh overwrote the live scalar.
	stale := Curve().NewScalar()
	if err := stale.UnmarshalBinary(beforeBytes[party.ID("a")]); err != nil {
		t.Fatalf("restore pre-refresh share: %v", err)
	}
	mixed := []*Partial{
		mustPartial(t, Share{ID: "a", Secret: stale}, ct),
		mustPartial(t, sharesAfter[party.ID("b")], ct),
		mustPartial(t, sharesAfter[party.ID("c")], ct),
	}
	if _, err := Combine(gAfter, ct, mixed); err == nil {
		t.Fatal("a pre-refresh share combined with post-refresh shares — refresh does not compartmentalise epochs")
	}
	t.Logf("group key preserved across refresh; all %d quorums of new shares open the old ciphertext; mixed-epoch quorum refused", len(combinations(ids(), quorum)))
}

// TestKeygenRequiresEveryParty records a real operational limitation rather
// than a property: the distributed key generation is all-n. Every party must be
// online for the ceremony and for a refresh, even though only a quorum is
// needed to decapsulate afterwards.
func TestKeygenRequiresEveryParty(t *testing.T) {
	parties := ids()
	present := parties[:n-1] // one node is down
	// Every party that IS up still believes the committee is all n, which is
	// exactly the operational situation: the absent node is expected, not
	// deconfigured. Only the present ones get handlers.
	_, err := test.RunProtocolWithTimeout(t, present, []byte("tkem-dkg-missing"), 5*time.Second, func(id party.ID) protocol.StartFunc {
		return frost.Keygen(Curve(), id, parties, frostDegree)
	})
	if err == nil {
		t.Fatal("keygen completed with a party absent — update the operational note, this limitation is gone")
	}
	t.Logf("keygen with %q absent fails as expected: %v", parties[n-1], err)
	t.Log("OPERATIONAL: key generation and refresh are all-n. Decapsulation is t-of-n.")
}

func mustPartial(t *testing.T, sh Share, ct *Ciphertext) *Partial {
	t.Helper()
	p, err := PartialDecapsulate(rand.Reader, sh, ct)
	if err != nil {
		t.Fatalf("partial from %s: %v", sh.ID, err)
	}
	return p
}

func mustMarshal(t *testing.T, m interface{ MarshalBinary() ([]byte, error) }) []byte {
	t.Helper()
	b, err := m.MarshalBinary()
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	return b
}

func asErrBadPartial(err error, out *ErrBadPartial) bool {
	for err != nil {
		if e, ok := err.(ErrBadPartial); ok {
			*out = e
			return true
		}
		u, ok := err.(interface{ Unwrap() error })
		if !ok {
			return false
		}
		err = u.Unwrap()
	}
	return false
}
